### PR TITLE
fix: Fix broken test case

### LINKED ISSUE #559: stacks-coordinator bitcoin_wallet::tests::fulfill_peg_out_change is failing

### PR DESCRIPTION
**Pull request by netrome**
Closes #559

### CODE REVIEW

**Review by stjepangolemac — APPROVED** [review]

File: stacks-coordinator/src/bitcoin_wallet.rs [hunk 1]
```diff
@@ -266,7 +266,7 @@ mod tests {
         assert_eq!(btc_tx.input.len(), 7);
         assert_eq!(btc_tx.output.len(), 3); // We have change!
         assert_eq!(btc_tx.output[0].value, 0);
-        assert_eq!(btc_tx.output[1].value, 10000);
```
Comment (jferrant) [inline stacks-coordinator/src/bitcoin_wallet.rs:269]: THis no longer actually tests the issue. we need to check the 3rd output as well.
